### ISSUE TITLE
unable to upload to game

### ISSUE THREAD

**Issue by linuxgruven** [ayecue/greybel-vs#107]
Asks for steam password, after entered returns an error

**Comment by linuxgruven** [comment]
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Comment by linuxgruven** [comment]
Unexpected error: Request timed out
Error: Request timed out
    at Object.Promises.timeoutPromise (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/node_modules/@doctormckay/stdlib/components/promises.js:12:12)
    at Object.Promises.timeoutCallbackPromise (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/node_modules/@doctormckay/stdlib/components/promises.js:87:25)
    at SteamUser.getAppOwnershipTicket (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/node_modules/steam-user/components/appauth.js:141:26)
    at /home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/node_modules/steam-user/components/appauth.js:94:9
    at /home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/node_modules/@doctormckay/stdlib/components/promises.js:26:25
    at new Promise (<anonymous>)
    at Object.Promises.timeoutPromise (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/node_modules/@doctormckay/stdlib/components/promises.js:14:9)
    at Object.Promises.timeoutCallbackPromise (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/node_modules/@doctormckay/stdlib/components/promises.js:87:25)
    at Object.Promises.callbackPromise (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/node_modules/@doctormckay/stdlib/components/promises.js:69:18)
    at SteamUser.createAuthSessionTicket (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/node_modules/steam-user/components/appauth.js:88:26)
    at /home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:611313
    at new Promise (<anonymous>)
    at ul.getAppTicket (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:611230)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ul.login (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:613369)
    at ul.initializeGameSession (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:613173)
    at ul.getLoginPayload (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:613007)
    at ul.runCommand (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:613981)
    at e.<computed>.n.<computed>.createTerminal (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:892150)
    at e.<computed>.n.<computed>.getTerminalPID (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:892075)
    at e.<computed>.n.<computed>.createFile (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:892362)
    at Wy.import (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:894765)
    at Py.createImporter (/home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:894956)
    at /home/brian/.vscode/extensions/ayecue.greybel-vs-1.9.2/extension.js:1:902984

**Comment by ayecue** [comment]
Hey, so from the error message it looks like the request related to getting the app ownership ticket timed out. I also tried to upload files earlier and it didn't work for me either. I'll take a look if there is an issue but sometimes the steam network is just kinda slow and the timeouts of the package I am using which is https://github.com/DoctorMcKay/node-steam-user. I'll get back to you if there are any news.

**Comment by ayecue** [comment]
I've updated the client version, related to importing files into the game, to a newer one. It includes a more lenient timeout policy and some other changes. Could you please try again if you can upload any files?

**Comment by linuxgruven** [comment]
Tried again no files were getting uploaded. This time I never got an email from steam with a steam code

**Comment by ayecue** [comment]
To which target are you trying to import to btw? public, nightly or local?

If it's local which version do you have installed?

**Comment by linuxgruven** [comment]
nightly online...thought local was broken?

**Comment by ayecue** [comment]
Yeah I noticed nightly is broken since there are a few changes when it comes to message ids. I am currently preparing an update for nightly since the merge is happening soon so therefore it makes sense to make everything working for that. I'll give an update once that is merged.

> thought local was broken

Well the issue with local got fixed at least for the issue with no files existing so it should work for the public version. The issue related to disconnecting the game client cannot be fixed. That is due to how the Grey Hack server works. So for example for local you have to do the following:
- start game (that will start a local game server)
- run the import of the extension
- reboot game pc with the return to title screen option
- start game
- profit

For public and nightly you also have to do "reboot game pc with return to title screen option" if you have a session going while using the extension. You can upload scripts without having the game open though at least for public and nightly.

But there might be a way by keeping the session open and by that avoiding the disconnect issue. But that is rather a feature. For now this is pretty much the intended way.

**Comment by ayecue** [comment]
With the new version released now the import feature should work again. At least from my testing. Both local and public.

The newest GreyHack version also seems to auto reconnect so the issue described above doesn't exist anymore.
