### ISSUE TITLE
Greybel: build leads to silent error

### ISSUE THREAD

**Issue by MadbHatter** [ayecue/greybel-vs#157]
Steps to reproducte:
- Installed Greybel VS (No other Extensions)
- Create new file hello_world.src `print("Hello world")`
- Greybel: build
- Nothing happens

What am I doing wrong?

```
The follwing is printed in Extension Host:
2023-12-11 03:34:04.445 [error] TypeError: Cannot read properties of undefined (reading 'fsPath')
	at c:\Users\Alexa\.vscode\extensions\ayecue.greybel-vs-2.1.5\extension.js:1:773186
	at c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:20799
	at Object.edit (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:55578)
	at c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:20786
	at d.h (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:140094)
	at d.$executeContributedCommand (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:140954)
	at l.S (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:10829)
	at l.Q (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:10595)
	at l.M (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:9685)
	at l.L (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:8764)
	at f.value (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:7567)
	at n.y (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
	at n.fire (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
	at o.fire (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:14039)
	at f.value (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:7903)
	at n.y (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
	at n.fire (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
	at o.fire (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:14039)
	at MessagePortMain.<anonymous> (c:\Users\Alexa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:6183)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

**Comment by MadbHatter** [comment]
I tested some other versions and the error still happend
- 2.1.4
- 2.0.0
- 1.10.3
- 1.5.2

**Comment by MadbHatter** [comment]
Sadly that didn't fix this issue for me.
At least now it is no longer a silent error and instead shows a error message in a MessageBox.

![Screenshot 2023-12-14 032548](https://github.com/ayecue/greybel-vs/assets/3505491/4000d88c-a909-41aa-92b0-c143f73751fb)

**Comment by MadbHatter** [comment]
I just tested all three and the following happens:
Via F1 or CTRL+SHIFT+P -> Error.
Context Menu in Code Editor -> Functions correctly.
Context Menu in File Explorer -> Functions correctly.

**Comment by MadbHatter** [comment]
I guess that is the same reason why Greybel: Refresh does not work either via F1?
Is it not possible to just get the current active editor tab/window and get the file path from there?

**Comment by MadbHatter** [comment]
So I did the follwing:

Added this line to the build command:
`let fsPath = (typeof eventUri === 'undefined') ? vscode.window.activeTextEditor.document.fileName : eventUri.fsPath ;`
and replaced all references to eventUri.fsPath with fsPath.

It seems to work fine that way (but that was a 1 minute hack).
