### ISSUE TITLE
Trying to open files not there

### ISSUE THREAD

**Issue by linuxgruven** [ayecue/greybel-vs#243]
I keep getting the following errors
Error: ENOENT: no such file or directory, open '/home/brian/Documents/GitHub/x/home/tux/src/0.src'
    at async open (node:internal/fs/promises:638:25)
    at async Object.readFile (node:internal/fs/promises:1266:14)
    at async K_.fetchTextDocument (/home/brian/.vscode/extensions/ayecue.greybel-vs-2.4.11/node_modules/greybel-languageserver/index.js:326:38355)
    at async K_.getTextDocument (/home/brian/.vscode/extensions/ayecue.greybel-vs-2.4.11/node_modules/greybel-languageserver/index.js:326:38643)
    at async F_.open (/home/brian/.vscode/extensions/ayecue.greybel-vs-2.4.11/node_modules/greybel-languageserver/index.js:326:26979)
    at async r (/home/brian/.vscode/extensions/ayecue.greybel-vs-2.4.11/node_modules/greybel-languageserver/index.js:326:25237)
    at async zo.getImports (/home/brian/.vscode/extensions/ayecue.greybel-vs-2.4.11/node_modules/greybel-languageserver/index.js:326:25341)
    at async gb (/home/brian/.vscode/extensions/ayecue.greybel-vs-2.4.11/node_modules/greybel-languageserver/index.js:110:361661)
    at async mb.buildTypeMap (/home/brian/.vscode/extensions/ayecue.greybel-vs-2.4.11/node_modules/greybel-languageserver/index.js:110:363918)
    at async mb.lookupTypeInfo (/home/brian/.vscode/extensions/ayecue.greybel-vs-2.4.11/node_modules/greybel-languageserver/index.js:110:364003) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/brian/Documents/GitHub/x/home/tux/src/0.src'
}
for files/folders no longer there

**Comment by linuxgruven** [comment]
about every 3-5 minutes I get this
![error](https://github.com/user-attachments/assets/d190cd73-4218-4ef1-a6c7-d8e2ee7b1722)

**Comment by linuxgruven** [comment]
I just did this for now
![error2](https://github.com/user-attachments/assets/59f0e327-b43c-4599-9aec-123838cab850)

**Comment by ayecue** [comment]
Interesting. I tried replicating it by deleting a file that got imported into another file. But it seems to work fine for me. Anyway looking at the language server code I can see that there is the possibility of it crashing if files don't exist. I've added a fix and updated the extension to use the latest version. The issue should not occur in the future anymore.

The log `Error: ENOENT: no such file or directory` may still occur in the future though. But it should be only visible in the developer console.

> I just did this for now ![error2](https://private-user-images.githubusercontent.com/13845037/359164939-59f0e327-b43c-4599-9aec-123838cab850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODYyNDIsIm5iZiI6MTcyNDA4NTk0MiwicGF0aCI6Ii8xMzg0NTAzNy8zNTkxNjQ5MzktNTlmMGUzMjctYjQzYy00NTk5LTlhZWMtMTIzODM4Y2FiODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE2NDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZTM1YzE0MTM2ZTQ1OGU4YmJkZDhjZTJiMTIwZTczZmY4YzNiYjgzZDlmYTFkMWVlMjUyYzA1ODQwMjAzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NG8miPERo8KIWCtA2CBTLncGLYro2Hf018uqKGSLWVg)

This won't have any influence on those error popups you showed. This silencing of error popups is only for the error thrown by the interpreter if there are mistakes in the code or that sort.

Anyway I hope this will fix the issue for you as well. In case it reoccurs post 2.4.12 feel free to reopen the ticket. Also thanks for reporting.

**Comment by ayecue** [comment]
@linuxgruven FYI I made another fix which should fix the actual issue you had yesterday. It was caused when there was invalid syntax at some point.
